sonar.projectKey=insurance-app
sonar.projectName=Insurance Portal

sonar.sources=.
sonar.exclusions=node_modules/**

sonar.host.url=http://32.236.9.124:9000

sonar.token=squ_8ee72e8fd6ed70b5ef1b371c29687d584a7f3319
