sonar.projectKey=insurance-app
sonar.projectName=Insurance Portal

sonar.sources=.
sonar.exclusions=node_modules/**

sonar.host.url=http://54.66.171.100:9000

sonar.token=sqp_6dc0a5c1ca7dfeaeb639aa599555cb2812f01428
