name: Insurance Portal CI/CD

on:
  push:
    branches:
      - master

jobs:

  build-test-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Verify Project Files
      run: |
        ls -la
        test -f server.js
        test -f Dockerfile
        test -f public/index.html

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Start Validation
      run: |
        node --check server.js

    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/insurance-portal:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/insurance-portal:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          docker pull ${{ secrets.DOCKER_USERNAME }}/insurance-portal:latest

          docker stop insurance-app || true
          docker rm insurance-app || true

          docker run -d \
          --name insurance-app \
          -p 80:3000 \
          ${{ secrets.DOCKER_USERNAME }}/insurance-portal:latest
